name 'kafka_node'
maintainer 'flugel.it'
maintainer_email 'infradevs@flugel.it'
license 'MIT License'
description 'Installs/Configures kafka_node'
long_description 'Installs/Configures kafka_node'
version '0.2.0'

depends 'java'
depends 'kafka'
